### ISSUE TITLE
Showing malicious files

### ISSUE THREAD

**Issue by SavageTesla** [YTEC-info/CH341A-Softwares#7]
download shows malicious files

**Comment by YTEC-info** [comment]
False positive, there is no virus. If you want to feel safe, run it on a virtualized system.

**Comment by lvent** [comment]
No false positive. Actually has multiple trojans. Tested and confirmed in a VM. 
https://www.virustotal.com/gui/file/53b918affeea505c954b4b86441fcd5ceec4b254e1b711cdf7fd096706fcd1f0/detection
![image](https://github.com/user-attachments/assets/f39a2142-d08a-43f0-ae99-e6a21e37fe37)

**Comment by YTEC-info** [comment]
I don't trust any antivirus :)

I saw that the suspicion is about the drivers for Windows, perhaps because these drivers are not signed. I've been using these programs for many years and haven't noticed any abnormal behavior. If any security expert demonstrates a real case of an attack on Windows systems, I will reopen the issue.

Again, if you're concerned about security, use Windows programs in a virtual system, or better yet, use only the excellent open source options for Linux (flashrom and IMSprog)

**Comment by roozerxc** [comment]
> No false positive. Actually has multiple trojans. Tested and confirmed in a VM. https://www.virustotal.com/gui/file/53b918affeea505c954b4b86441fcd5ceec4b254e1b711cdf7fd096706fcd1f0/detection ![image](https://private-user-images.githubusercontent.com/6698380/364078969-f39a2142-d08a-43f0-ae99-e6a21e37fe37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzAwODcsIm5iZiI6MTcyODQyOTc4NywicGF0aCI6Ii82Njk4MzgwLzM2NDA3ODk2OS1mMzlhMjE0Mi1kMDhhLTQzZjAtYWU5OS1lNmEyMWUzN2ZlMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMjMyMzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzE3NmI0Nzg2MTk1Y2YxMjNmNTU3M2JhM2E1YmNiMzM2NmYwNTNmNzA0YWZjZDFjMWJmMGI3NjI2YjFjZmFhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QDQqFhWXSg7ROfZ1fLfuZhmtznEtA9kANUUQ3h7DtNk)

Tried Neoprogrammer on my laptop and indeed it had infected all of my EXEs. I'm going to reinstall

**Comment by YTEC-info** [comment]
To centralize the discussion on this, participate in issue #18
